### PR TITLE
Adding some data related to dog licenses

### PR DESCRIPTION
**Pull request by cwickham**
Planning to add:
- [x] Tax data from IRS
- [x] Population data from census (actually got it from NYC Open Data)
- [x] Parks locations by zip

### CODE REVIEW

**Comment by cwickham** [comment]
@lwjohnst86 I'm assuming this is the right workflow for https://github.com/merely-useful/merely-useful.github.io/pull/144, let me know if not.

More commits coming, I'll ping you when ready.

**Comment by lwjohnst86** [comment]
@cwickham yes! Looks good!

**Comment by cwickham** [comment]
@lwjohnst86 ready for review/merge. This is all I'm planning to add at this point.

**Comment by lwjohnst86** [comment]
Amazing, looks good, thanks!

**Pull request merged**
